#!/bin/sh
# Some tools will choke on the YAML files generated by PyYAML;
# in particular on a section like this one:
#
# service:
#   ports:
#   - 8000:5000
#
# This script adds two spaces in front of the dash in those files.
# Warning: it is a hack, and probably won't work on some YAML files.
[ -f "$COMPOSE_FILE" ] || {
    echo "Cannot find COMPOSE_FILE"
    exit 1
}
sed -i 's/^  -/    -/' $COMPOSE_FILE

