apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  selector:
    matchLabels:
      app: hasher
  replicas: 3
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: "dockercoins/hasher:v0.1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  type: LoadBalancer
  selector:
    app: hasher
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80