apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: coffees.container.training
spec:
  group: container.training
  version: v1alpha1
  scope: Namespaced
  names:
    plural: coffees
    singular: coffee
    kind: Coffee
    shortNames:
    - cof
  additionalPrinterColumns:
  - JSONPath: .spec.taste
    description: Subjective taste of that kind of coffee bean
    name: Taste
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - taste
          properties:
            taste:
              description: Subjective taste of that kind of coffee bean
              type: string
