---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: rocky-test
  name: rocky-full-access
rules:
- apiGroups: ["", extensions, apps]
  resources: [deployments, replicasets, pods, services, ingresses, statefulsets]
  verbs: [get, list, watch, create, update, patch, delete] # You can also use [*]
