# This removes the haproxy Deployment.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    $patch: delete
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: haproxy
