version: "3.3"

services:

  prometheus:
    image: prom/prometheus:v1.4.1
    ports:
      - "9090:9090"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml

  node:
    image: prom/node-exporter
    command: --path.procfs /host/proc --path.sysfs /host/proc --collector.filesystem.ignored-mount-points "^(sys|proc|dev|host|etc)($$|/)"
    deploy:
      mode: global
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"

  cadvisor:
    image: google/cadvisor
    deploy:
      mode: global
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker:/var/lib/docker"

configs:
  prometheus:
    file: ../prom/prometheus.yml
