service:
  type: ClusterIP
persistence:
  enabled: false
mariadb:
  master:
    persistence:
      enabled: false
ingress:
  enabled: true
  certManager: true
  hosts:
  - name: user1-wp.ingress.workshop.paulczar.wtf
  path: /
  tls:
    - hosts:
      - user1-wp.ingress.workshop.paulczar.wtf
      secretName: wordpress-tls